sudo: false

language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s build/logs/ https://codecov.io/bash)
