sudo: false

language: php

php:
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s build/logs/ https://codecov.io/bash)
