name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.0, 7.4, 7.3, 7.2, 7.1 ]
        laravel: [ 8.*, 7.*, 6.*, 5.8.*, 5.7.*, 5.6.*, 5.5.*, 5.4.* ]
        include:
          - laravel: 8.*
            testbench: 6.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 6.*
            testbench: 4.*
          - laravel: 5.8.*
            testbench: 3.8.*
          - laravel: 5.7.*
            testbench: 3.7.*
          - laravel: 5.6.*
            testbench: 3.6.*
          - laravel: 5.5.*
            testbench: 3.5.*
          - laravel: 5.4.*
            testbench: 3.4.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: dom, curl, libxml, mbstring, zip
            tools: composer:v2
            coverage: none

      -   name: Install dependencies
          run: |
            composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
            composer update --prefer-dist --no-interaction --no-progress
      -   name: Execute tests
          run: vendor/bin/phpunit
