name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: true
      matrix:
        php: [7.1]
        laravel: [^5.4]
        include:
          - testbench: ^3.4

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            extensions: dom, curl, libxml, mbstring, zip
            tools: composer:v2
            coverage: none

      -   name: Install dependencies
          run: |
            composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
            composer update --prefer-dist --no-interaction --no-progress
      -   name: Execute tests
          run: vendor/bin/phpunit
